spring.application.name=guvi.lms

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=your_username
spring.datasource.password=your_password

jwt.secret=your_jwt_secret
jwt.expiration=86400000

server.port=8080
file.upload-dir=uploads